# EC Notebook for Week 2: Blocking and Conditionals

This extra credit Python notebook will let you practice the material you saw in lecture!  Completing all parts of this notebook will earn +1 extra credit point to your grade in STAT 107!

This notebook is worth +1 if turned in before 11:59pm on **Friday, Feb. 7**.

## 1. Loading pandas and importing data

For this notebook, we will continue to use the "Hello" dataset introduced last lecture!

Using your @illinois.edu address, download the dataset as a CSV and **make sure to save or move it to the same directory as this notebook**: https://docs.google.com/spreadsheets/d/1uS6OoVsaCNEDwi-ozOXJe7Vn08M-41k7W1cdAlwLIiY/edit?usp=sharing

Use the following cell to load the pandas library and read the DataSet as a DataFrame:

In [2]:
import pandas as pd
df = pd.read_csv('Hello Dataset - Dataset.csv')

## 2. Creating a Control Group

In lecture, we worked out a puzzle.  From the lecture handout:

> Use Python to create a control group of 20 students, using blocking to control for the influence we suspect having more than 1 siblings might have.  Make sure you have an equal number of students with 0 or 1 sibling and an equal number of students with 2 or more siblings.

We will complete the code in a notebook this in four separate steps to get practice on each part.

### 2.1: Sibling Block #1 -- Zero or One Siblings

Creating a DataFrame that contains all students with 0 or 1 siblings and call it `block1`:

In [3]:
block1 = df[df['Siblings']<=1]



# Show a few rows to check if the block has the data we expect:
block1.sample(n=3)

,Name,Major,School Year,Phone,Computer,Holes in a Straw,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality,Pineapple on Pizza
11,Bohan,NaN,Freshman,iPhone,Windows-based computer,1.0,0,0,0,0,...,Yes,Some Python -- I have had one class or written...,1,7.0,0,7.0,5,5,Introvert,Yes
23,Brandon,Math,Sophomore,iPhone,Windows-based computer,1.0,0,0,0,0,...,Yes,Some Python -- I have had one class or written...,0,5.0,1,7.0,4,2,NaN,No
70,Claude,Communicaton,Junior,Android,Windows-based computer,1.0,0,0,0,0,...,No,No programming background -- is Python Taylor ...,1,2.0,1,6.0,4,6,Introvert,No

### 2.2: Sibling Block #2 -- Two or More Siblings

Create a DataFrame that contains all students with 2 or more siblings and call it `block2`:

In [4]:
block2 = df[df['Siblings']>1]


# Show a few rows to check if the block has the data we expect:
block2.sample(n=3)

,Name,Major,School Year,Phone,Computer,Holes in a Straw,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality,Pineapple on Pizza
29,Isaiah,Economics,Senior,iPhone,Windows-based computer,1.0,1,0,0,0,...,Yes,Some Python -- I have had one class or written...,3,2.0,2,7.0,15,24,Introvert,No
53,Vada,Advertising,Sophomore,iPhone,Mac OS X-based computer,1.0,0,1,0,0,...,No,No programming background -- is Python Taylor ...,1,2.0,2,8.0,15,20,Extrovert,Yes
54,Bakhtiar,Economics,Senior,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,Yes,Some Python -- I have had one class or written...,5,2.0,2,8.0,5,8,Introvert,No

### 2.3: Selecting equal sized groups from block1 and block2

**Randomly** select an equal number of students from each of `block1` and `block2` and store them in `control1` and `control2`.  We will combine both groups to make the full control group:

In [5]:
control1 = block1.sample(n=10)


# Show a few rows to check if the control group has the data we expect:
control1.sample(n=3)

,Name,Major,School Year,Phone,Computer,Holes in a Straw,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality,Pineapple on Pizza
55,Ben,any CS,Sophomore,Android,Linux-based computer,20.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",2,3.0,0,8.0,2,0,Introvert,No
4,Chen,Information Science,Freshman,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",1,4.0,0,8.0,20,20,Extrovert,Yes
72,Shawn,Computer Science + Statistics,Freshman,iPhone,Windows-based computer,1.0,1,0,0,0,...,Yes,"No Python, but I've done some programming in o...",0,2.0,1,7.0,10,7,Extrovert,No

In [6]:
control2 = block2.sample(n=10)



# Show a few rows to check if the control group has the data we expect:
control2.sample(n=3)

,Name,Major,School Year,Phone,Computer,Holes in a Straw,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality,Pineapple on Pizza
41,Raina,Math + Business,Senior,iPhone,Windows-based computer,1.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",1,2.0,2,6.5,7,33,Introvert,No
1,Karle,Statistics,Other,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,Yes,Some Python -- I have had one class or written...,20,1.0,2,7.0,20,24,Extrovert,Yes
40,Tim,Aerospace Engineering,Freshman,iPhone,Windows-based computer,2.0,1,1,0,0,...,Yes,Some Python -- I have had one class or written...,1,0.5,2,7.0,3,3,Introvert,Yes

#### 2.4. [CHALLENGE!] -- Combine the two sub-groups into a single control group

Use the following code to merge the contents of `control1` and `control2` together into one large group called `control`.  To do this, you will need to use the `pd.concat` command that you can **find on your cheat sheet**.

In [7]:
control = pd.concat([control1,control2])



# Show the full control group (it should have 20 rows, mixed number of siblings)
control

,Name,Major,School Year,Phone,Computer,Holes in a Straw,Has Dogs,Has Cats,Has Fish,Has Chickens,...,Programmed before?,Python Background,Statistics Courses,Hours Studying,Siblings,Hours of Sleep,Shoes Owned,People Texted Yesterday,Personality,Pineapple on Pizza
71,yuchen,electric engineering,Freshman,iPhone,Windows-based computer,1.0,1,0,0,0,...,Yes,"No Python, but I've done some programming in o...",1,3.0,1,7.0,3,3,Introvert,Yes
87,Howe,Statistics,Sophomore,iPhone,Windows-based computer,1.0,0,1,0,0,...,No,No programming background -- is Python Taylor ...,2,4.0,1,7.0,5,20,Introvert,Yes
72,Shawn,Computer Science + Statistics,Freshman,iPhone,Windows-based computer,1.0,1,0,0,0,...,Yes,"No Python, but I've done some programming in o...",0,2.0,1,7.0,10,7,Extrovert,No
4,Chen,Information Science,Freshman,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",1,4.0,0,8.0,20,20,Extrovert,Yes
86,Nick,Statistics,Sophomore,iPhone,Mac OS X-based computer,1.0,1,0,0,0,...,Yes,"No Python, but I've done some programming in o...",3,3.0,1,9.0,3,4,Introvert,No
34,Nima,Information Science,Sophomore,iPhone,Windows-based computer,2.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",0,3.0,1,8.0,5,5,Introvert,Yes
35,Michelle,Statistics + Computer Science,Sophomore,iPhone,Mac OS X-based computer,1.0,1,0,0,0,...,Yes,Some Python -- I have had one class or written...,3,5.0,1,7.0,19,11,Introvert,No
55,Ben,any CS,Sophomore,Android,Linux-based computer,20.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",2,3.0,0,8.0,2,0,Introvert,No
23,Brandon,Math,Sophomore,iPhone,Windows-based computer,1.0,0,0,0,0,...,Yes,Some Python -- I have had one class or written...,0,5.0,1,7.0,4,2,NaN,No
28,Justin,Statistics,Junior,Android,Windows-based computer,2.0,1,0,0,0,...,Yes,"No Python, but I've done some programming in o...",3,3.0,1,8.0,9,5,Introvert,Yes
41,Raina,Math + Business,Senior,iPhone,Windows-based computer,1.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",1,2.0,2,6.5,7,33,Introvert,No
27,Brianna,Global Studies,Junior,iPhone,Windows-based computer,1.0,0,1,0,0,...,Yes,Some Python -- I have had one class or written...,1,2.0,4,7.0,15,20,Extrovert,Yes
67,Jose Hernandez,Political Science,Sophomore,iPhone,Mac OS X-based computer,2.0,0,0,0,0,...,No,No programming background -- is Python Taylor ...,1,1.0,3,7.5,12,7,Introvert,No
53,Vada,Advertising,Sophomore,iPhone,Mac OS X-based computer,1.0,0,1,0,0,...,No,No programming background -- is Python Taylor ...,1,2.0,2,8.0,15,20,Extrovert,Yes
40,Tim,Aerospace Engineering,Freshman,iPhone,Windows-based computer,2.0,1,1,0,0,...,Yes,Some Python -- I have had one class or written...,1,0.5,2,7.0,3,3,Introvert,Yes
21,Yosra,Economics,Freshman,iPhone,Mac OS X-based computer,2.0,0,0,0,0,...,Yes,"No Python, but I've done some programming in o...",0,2.0,2,5.0,9,9,Extrovert,No
29,Isaiah,Economics,Senior,iPhone,Windows-based computer,1.0,1,0,0,0,...,Yes,Some Python -- I have had one class or written...,3,2.0,2,7.0,15,24,Introvert,No
1,Karle,Statistics,Other,iPhone,Mac OS X-based computer,1.0,0,0,0,0,...,Yes,Some Python -- I have had one class or written...,20,1.0,2,7.0,20,24,Extrovert,Yes
84,Feliks,Statistics,Junior,iPhone,Windows-based computer,1.0,1,0,0,0,...,Yes,Some Python -- I have had one class or written...,2,3.5,3,8.3,4,8,Introvert,No
64,Neil,Information Technology,Junior,iPhone,Mac OS X-based computer,1.0,1,0,0,0,...,Yes,Some Python -- I have had one class or written...,3,2.0,2,7.0,20,15,Extrovert,No

In [8]:
## == TEST CASES for Puzzle 2 ==
# - This read-only cell contains test cases for your previous cells.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.

assert( len(control) == 20 ), "Your control group must only have 20 courses in it."
assert( len(control[control.Siblings < 2] ) == 10 ), "Your control group must only have 10 people with 0-1 siblings in it."
assert( len(control[control.Siblings >= 2] ) == 10 ), "Your control group must only have 10 people with 2+ siblings in it."


## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:

tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

ðŸŽ‰ All tests passed! ðŸŽ‰

## Submit Your Work!

Make sure to **Save and Checkpoint** your notebook, exit Jupyter, and submit your work! :)